steps:
  - name: build
    image: gcr.io/kaniko-project/executor:debug
    commands:
      - >
        /kaniko/executor
        --context=dir:///woodpecker/src
        --dockerfile=Dockerfile
        --destination=git.lab.home/eurusik/eurusik.tech:${CI_COMMIT_SHA:0:7}
        --destination=git.lab.home/eurusik/eurusik.tech:latest
        --insecure
        --skip-tls-verify
    environment:
      DOCKER_CONFIG: /kaniko/.docker
    secrets: [registry_user, registry_password]

  - name: deploy
    image: bitnami/kubectl:latest
    commands:
      - kubectl set image deployment/eurusik-app eurusik-app=git.lab.home/eurusik/eurusik.tech:${CI_COMMIT_SHA:0:7} -n eurusik-app
      - kubectl rollout status deployment/eurusik-app -n eurusik-app --timeout=120s

when:
  branch: main
  event: push
