steps:
  - name: build
    image: gcr.io/kaniko-project/executor:debug
    commands:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"git.lab.home\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - >
        /kaniko/executor
        --context=dir:///woodpecker/src
        --dockerfile=Dockerfile
        --destination=git.lab.home/eurusik/eurusik.tech:${CI_COMMIT_SHA:0:7}
        --destination=git.lab.home/eurusik/eurusik.tech:latest
        --insecure
        --skip-tls-verify
    environment:
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASSWORD:
        from_secret: registry_password

when:
  - branch: main
    event: push
