name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:cli
      options: --privileged
    steps:
      - name: Install Node.js and Git
        run: apk add --no-cache nodejs npm git

      - name: Checkout
        run: |
          git clone --depth 1 http://admin:${{ secrets.REGISTRY_PASSWORD }}@git.lab.home/eurusik/eurusik.tech.git .

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build app
        run: npm run build

      - name: Build and push Docker image
        run: |
          docker build -t git.lab.home/eurusik/eurusik.tech:latest .
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login git.lab.home --username ${{ secrets.REGISTRY_USER }} --password-stdin
          docker push git.lab.home/eurusik/eurusik.tech:latest
