name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag to rollback to (e.g., a1b2c3d-1234567890)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate image exists
      run: |
        echo "Checking if image exists: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image-tag }}"
        # Attempt to pull image metadata to verify it exists
        docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image-tag }} || exit 1

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: ghcr.io/eurusik/eurusik:.*|image: ghcr.io/eurusik/eurusik:${{ inputs.image-tag }}|g" k8s/deployment.yaml
        echo "Rolled back image tag to: ${{ inputs.image-tag }}"

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yaml
        git commit -m "rollback: revert to image tag ${{ inputs.image-tag }}"
        git push

    - name: Trigger ArgoCD sync
      run: |
        echo "✅ Rollback committed. ArgoCD will auto-sync within 3 minutes."
        echo "To sync immediately, run: argocd app sync eurusik-app"
